name: "Example Workflow with failure() condition"
on: [push]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: This step will intentionally fail
        run: exit 1

      - name: This step runs only if the previous step fails
        if: failure()
        run: echo "Previous step failed, running this step."

      - name: This step runs regardless of previous step's success or failure
        run: echo "This runs no matter what."

      - name: This step runs only if the previous steps have succeeded
        if: success()
        run: echo "All previous steps succeeded, running this step."
