# its a key value pair with python syntax

# first it will contain a name that will be name of this file and

name: hello world

# then it need to define at which event this will be triggered like create of branch del of branch push pull merge

on:
  #trigger this whenever the push event is done on the beneath branches
  push: # here the event name
    branches: #whenever the above written event happens on the beneath branches the jobs will run
      - main
      - develop
  #trigger this whenever the pull event is done on the given branches

  pull:
    branches: #whenever the above written event happens on the beneath branches the jobs will run
      - main
      - develop

 workflow-_dispatch:   # just creates a button at github to run this file without above events
jobs: # here starts the job section
    hello:   # the name you have given to your first job, its easier to debug then
      runs-on: ubuntu-latest    # on which runner it will run since each job to run independently
      steps:
      - uses: actions/checkout@v2   # which action it is using as there are lot of pre built written by people so we use this and its like owner/repo@version or tag or branch
      - name: hello world   # name of the step
        run:  echo "hello world" # the command it will run
        shell : bash # which terminal it will use of the runner
   bye:   # the name you have given to your first job, its easier to debug then
      runs-on: ubuntu-latest    # on which runner it will run since each job to run independently
      steps:
      - name: Good Bye  # name
        run:  echo "Good Bye" # the command it will run
        shell : bash # which terminal it will use of the runner
