name: "hello world"

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop


jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "hello world"
        shell: bash

  bye:
    runs-on: ubuntu-latest
    steps:
      - name: Good Bye
        run: echo "Good Bye"
        shell: bash
